dynamic test

diff --git a/.github/workflows/always-fail.yaml b/.github/workflows/always-fail.yaml
--- a/.github/workflows/always-fail.yaml
+++ b/.github/workflows/always-fail.yaml
@@ -1,7 +1,26 @@
-name: GitHub Actions Demo
-on: [pull_request]
+name: Conditional PR Workflow
+
+on:
+  pull_request:
+    branches:
+      - master
+      - PR
+
 jobs:
-  always-fail:
+  check-branch:
     runs-on: ubuntu-latest
+
     steps:
-      - run: exit 1
+      - name: Checkout the repository
+        uses: actions/checkout@v2
+
+      - name: Fail PR if not targeting master
+        if: github.event.pull_request.base.ref != 'master'
+        run: |
+          echo "This PR is targeting the master branch, so it will fail."
+          exit 1 # Will make the workflow fail
+
+      - name: Succeed PR if targeting master
+        if: github.event.pull_request.base.ref == 'master'
+        run: |
+          echo "This PR is not targeting the master branch, so it will succeed."
